name: test.yml
on: push 
jobs: 
  tests:
    runs-on: ubuntu latest
    steps:
      - name: get Code
        uses: actions/checkout@v4
      - name: Install node js
        uses: actions/setup-node@v3
        with: 
            node-version: 18
      - name: installing dependencies
        run: npm ci
